2022-03-09 16:07:06,990 INFO    MainThread:176342 [wandb_setup.py:_flush():71] setting env: {'api_key': '***REDACTED***'}
2022-03-09 16:07:06,990 INFO    MainThread:176342 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-03-09 16:07:06,991 INFO    MainThread:176342 [wandb_setup.py:_flush():71] setting login settings: {'api_key': '***REDACTED***'}
2022-03-09 16:07:06,991 INFO    MainThread:176342 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-09 16:07:06,991 INFO    MainThread:176342 [wandb_init.py:_log_setup():371] Logging user logs to /home/haiduong/Documents/Project 3/TorchSemiSeg/CPS_Kaggle/wandb/run-20220309_160706-28agfjjf/logs/debug.log
2022-03-09 16:07:06,991 INFO    MainThread:176342 [wandb_init.py:_log_setup():372] Logging internal logs to /home/haiduong/Documents/Project 3/TorchSemiSeg/CPS_Kaggle/wandb/run-20220309_160706-28agfjjf/logs/debug-internal.log
2022-03-09 16:07:06,991 INFO    MainThread:176342 [wandb_init.py:init():404] calling init triggers
2022-03-09 16:07:06,992 INFO    MainThread:176342 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-03-09 16:07:06,992 INFO    MainThread:176342 [wandb_init.py:init():460] starting backend
2022-03-09 16:07:06,992 INFO    MainThread:176342 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-09 16:07:07,047 INFO    MainThread:176342 [backend.py:ensure_launched():216] starting backend process...
2022-03-09 16:07:07,051 INFO    MainThread:176342 [backend.py:ensure_launched():221] started backend process with pid: 176398
2022-03-09 16:07:07,052 INFO    MainThread:176342 [wandb_init.py:init():469] backend started and connected
2022-03-09 16:07:07,055 INFO    MainThread:176342 [wandb_init.py:init():533] updated telemetry
2022-03-09 16:07:07,064 INFO    MainThread:176342 [wandb_init.py:init():563] communicating current version
2022-03-09 16:07:07,951 INFO    MainThread:176342 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-09 16:07:07,951 INFO    MainThread:176342 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-09 16:07:08,364 INFO    MainThread:176342 [wandb_init.py:init():606] starting run threads in backend
2022-03-09 16:07:13,370 INFO    MainThread:176342 [wandb_run.py:_console_start():1810] atexit reg
2022-03-09 16:07:13,370 INFO    MainThread:176342 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-09 16:07:13,370 INFO    MainThread:176342 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-09 16:07:13,372 INFO    MainThread:176342 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-09 16:07:13,372 INFO    MainThread:176342 [wandb_init.py:init():633] run started, returning control to user process
2022-03-09 16:07:13,417 INFO    MainThread:176342 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-09 16:07:13,418 INFO    MainThread:176342 [wandb_run.py:_restore():1752] restore
